---
- name: Enable Apache2 modules
  community.general.apache2_module:
    name: rewrite
    state: present
  with_items:
    - rewrite
    - headers
    - env
    - dir
    - mime
  notify:
    - Restart Apache
