---
- name: Write Apache2 nextcloud.conf file
  ansible.builtin.template:
    src: apache2_nextcloud.conf.j2
    dest: "{{ nextcloud_apache2_config_path }}"
    mode: '0644'
  become: true
  notify:
    - Enable Nextcloud site
