---
- name: Write nginx.conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nextcloud_nginx_config_path }}"
    mode: '0644'
    backup: true
  become: true
  notify:
    - Restart nginx
