---
- name: Restart Apache
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Enable Apache Nextcloud site
  ansible.builtin.command: a2ensite nextcloud.conf

- name: Disable Apache Nextcloud site
  ansible.builtin.command: a2dissite nextcloud.conf
