---
- name: Enable Nextcloud site
  ansible.builtin.command: a2ensite nextcloud.conf

- name: Restart Apache
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
