---
- name: Restart Apache
  ansible.builtin.systemd:
    name: httpd
    state: restarted

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Enable Nextcloud site
  ansible.builtin.file:
    src: "{{ nextcloud_apache2_config_path }}"
    dest: /etc/apache2/sites-enabled/nextcloud.conf
    state: link
