---
name: Release
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

env:
  GALAXY_USERNAME: coredotbin

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Wait for a successful conclusion from the Lint workflow
      # before running the import
      - name: Wait for workflow
        uses: ArcticLampyrid/action-wait-for-workflow@v1.0.2
        with:
          workflow: Lint

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      # Galaxy uses CamelCase username but GitHub is all lowercase
      # This concatenates the versions together to work with
      # And triggers an import on Galaxy
      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ env.GALAXY_USERNAME }})
          $(echo ${{ github.repository }} | cut -d/ -f2)
